[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "morph"
version = "0.1.0"
description = "Test software in environments you don't physically have."
authors = [{name = "Adith"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.6.0",
    "fastapi>=0.110.0",
    "uvicorn>=0.29.0",
    "typer>=0.12.0",
    "rich>=13.7.0",
    "psutil>=5.9.8",
    "py-cpuinfo>=9.0.0",
    "distro>=1.9.0",
    "pyyaml>=6.0.1",
]

[project.scripts]
morph = "morph.cli.main:app"
