"""Executable Invariant Exporter.

Generates a regression guardrail test file (``test_morph_invariant.py``)
embedding the discovered safe envelope so CI re-checks it on every build.

Units follow the environment profile schema: ``safe_latency_ms`` in
milliseconds, ``safe_packet_loss`` in PERCENT (``network.packet_loss_percent``;
``2.0`` means 2 % of packets dropped), ``safe_cpu_quota`` as a fraction of one
core. The generated code passes these to :func:`morph.environment`.
"""

from __future__ import annotations

import re

_SAFE_VALUE_BY_PARAM = {
    "network.latency_ms": ("safe_latency_ms", "ms"),
    "network.packet_loss_percent": ("safe_packet_loss", "%"),
    "cpu.quota_percent": ("safe_cpu_quota", ""),
}


def _identifier(name: str) -> str:
    """Turn any project name into a valid, lowercase Python identifier fragment."""
    ident = re.sub(r"_+", "_", re.sub(r"\W", "_", name.strip().lower())).strip("_") or "service"
    if ident[0].isdigit():
        ident = f"p_{ident}"
    return ident


def generate_invariant_test_code(
    project_name: str = "service",
    command: str = "python3 -m apps.timeout test",
    safe_latency_ms: float = 160.0,
    safe_packet_loss: float = 1.0,
    safe_cpu_quota: float = 1.0,
    param_name: str = "network.latency_ms",
    boundary_estimate: float | None = None,
    divergence_summary: str | None = None,
    safe_value: float | None = None,
) -> str:
    """Generate executable ``test_morph_invariant.py`` source.

    ``param_name`` is the parameter the threshold search swept and
    ``safe_value`` its discovered safe bound; when ``safe_value`` is omitted it
    is taken from the matching ``safe_*`` argument (latency, packet loss or CPU
    quota). ``safe_packet_loss`` is in percent. The returned source always
    compiles: the command is embedded as a Python literal and the project name
    is sanitised into an identifier.
    """
    if not command or not command.strip():
        raise ValueError("command must not be empty")
    values = {
        "safe_latency_ms": safe_latency_ms,
        "safe_packet_loss": safe_packet_loss,
        "safe_cpu_quota": safe_cpu_quota,
    }
    unit = ""
    if safe_value is None:
        key, unit = _SAFE_VALUE_BY_PARAM.get(param_name, (None, ""))
        safe_value = values[key] if key else None
    else:
        unit = _SAFE_VALUE_BY_PARAM.get(param_name, (None, ""))[1]

    envelope = (
        f"{param_name} <= {safe_value:g}{unit}" if safe_value is not None
        else "the discovered safe envelope"
    )
    doc_summary = (
        f"Verifies {project_name} tolerates the discovered safe envelope\n"
        f"    ({envelope}; latency {safe_latency_ms:g} ms, packet loss {safe_packet_loss:g} %, "
        f"CPU quota {safe_cpu_quota:g})."
    )
    if boundary_estimate is not None:
        doc_summary += f"\n    Discovered failure boundary for {param_name}: ~{boundary_estimate:.1f}{unit}."
    if divergence_summary:
        safe_div = divergence_summary.replace('"""', "'''").replace("\n", "\n    ")
        doc_summary += f"\n    Divergence:\n    {safe_div}"

    test_name = f"test_{_identifier(project_name)}_environment_tolerance"

    return f'''"""Automated Environment Invariant Guardrail generated by Morph.

{doc_summary}
"""

import subprocess

import morph

TARGET_COMMAND = {command!r}


def run_target_command(cmd: str = TARGET_COMMAND) -> subprocess.CompletedProcess:
    """Execute the target command within the active environment."""
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)


def {test_name}():
    """Generated by Morph: verifies the service tolerates its safe envelope."""
    # Units: latency_ms in milliseconds; packet_loss in percent; cpu_quota as a
    # fraction of one core.
    with morph.environment(
        latency_ms={safe_latency_ms!r},
        packet_loss={safe_packet_loss!r},
        cpu_quota={safe_cpu_quota!r},
    ):
        proc = run_target_command()
        assert proc.returncode == 0, (
            f"Environment invariant violated: command failed with exit code {{proc.returncode}}.\\n"
            f"STDOUT: {{proc.stdout}}\\n"
            f"STDERR: {{proc.stderr}}"
        )
'''
