"""Executable Invariant Exporter.

Generates regression guardrail test files (test_morph_invariant.py)
embedding discovered operational thresholds and environment invariants.
"""

from __future__ import annotations


def generate_invariant_test_code(
    project_name: str = "service",
    command: str = "python3 -m apps.timeout test",
    safe_latency_ms: float = 160.0,
    safe_packet_loss: float = 0.01,
    safe_cpu_quota: float = 1.0,
    param_name: str = "network.latency_ms",
    boundary_estimate: float | None = 180.0,
    divergence_summary: str | None = None,
) -> str:
    """Generate executable test_morph_invariant.py Python code."""
    doc_summary = (
        f"Verifies {project_name} tolerates baseline environment conditions\n"
        f"    within the discovered safe envelope ({param_name} <= {safe_latency_ms})."
    )
    if boundary_estimate is not None:
        doc_summary += f"\n    Discovered failure boundary threshold: ~{boundary_estimate:.1f}."

    code = f'''"""Automated Environment Invariant Guardrail generated by Morph.

{doc_summary}
"""

import os
import subprocess
import pytest
import morph


def run_target_command(cmd: str = "{command}") -> subprocess.CompletedProcess:
    """Execute the target command within the active environment."""
    return subprocess.run(
        cmd,
        shell=True,
        capture_output=True,
        text=True,
    )


@pytest.mark.reliability
def test_{project_name.lower().replace('-', '_')}_environment_tolerance():
    """Generated by Morph: verifies service tolerates production baseline."""
    # Discovered safe envelope bounds
    with morph.environment(
        latency_ms={safe_latency_ms},
        packet_loss={safe_packet_loss},
        cpu_quota={safe_cpu_quota},
    ):
        proc = run_target_command()
        assert proc.returncode == 0, (
            f"Environment invariant violated: command failed with exit code {{proc.returncode}}.\\n"
            f"STDOUT: {{proc.stdout}}\\n"
            f"STDERR: {{proc.stderr}}"
        )


if __name__ == "__main__":
    print("[Morph Invariant] Running environment tolerance check...")
    with morph.environment(latency_ms={safe_latency_ms}, packet_loss={safe_packet_loss}):
        res = run_target_command()
        if res.returncode == 0:
            print("[Morph Invariant] PASS: System operated reliably within safe envelope.")
        else:
            print(
                f"[Morph Invariant] FAIL: System broke under boundary conditions (exit {{res.returncode}})."
            )
            print(res.stderr or res.stdout)
'''
    return code
